# -*- coding: utf-8 -*-
"""Untitled74.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0w0OgmwTceL1jw3uI974Pjwtam1EafT
"""

import streamlit as st
import joblib
import pandas as pd
import numpy as np
import os

# --- Model Loading ---

@st.cache_resource
def load_model(model_path):
    """Load the pre-trained scikit-learn model pipeline."""
    if not os.path.exists(model_path):
        st.error(f"Model file not found at: {model_path}")
        return None

    try:
        # Load the model
        pipeline = joblib.load(model_path)
        return pipeline
    except Exception as e:
        # If the version is still wrong, this will display the error,
        # but the code attempts to load it correctly.
        st.error(f"Error loading the model: {e}")
        return None

MODEL_FILE = 'trained_model (2).joblib'
pipeline = load_model(MODEL_FILE)


# --- Input Feature Definitions ---

# Numerical features
NUM_FEATURES = [
    'Runtime_Hours', 'Load_Factor', 'Cycles_Per_Shift', 'Energy_Consumption_kwh',
    'Last_Maintenance_Days', 'Vibration_X_RMS', 'Vibration_Y_RMS', 'Bearing_Temp_C',
    'Hydraulic_Pressure_psi', 'Motor_Current_Amp', 'Noise_dB', 'Oil_Quality_Index',
    'Gearbox_Torque_Nm', 'Latency_ms', 'Control_Unit_Error_Rate', 'Humidity_%',
    'Ambient_Temp_C', 'Cargo_Density_Index'
]

# Categorical features and their inferred categories
CAT_FEATURES = {
    'Equipment_Type': ['AGV', 'Crane', 'Swing', 'Hydraulic_Unit_B'],
    'Operator_Shift': ['Day', 'Night', 'Swing'],
    'Required_Spare_Part': ['Bearing_Pack_C', 'Hydraulic_Unit_B', 'Motor_Type_A']
}


# --- Streamlit App Layout and Logic ---

def main():
    """Main function to run the Streamlit application."""
    st.set_page_config(page_title="Predictive Maintenance - Spare Part Forecasting")

    st.title("🏭 Predictive Maintenance Model Deployment")
    st.subheader("Predicting the Required Spare Part (Y Variable)")

    if pipeline is None:
        st.warning("Model could not be loaded. Please check the version in requirements.txt.")
        return

    # User Input Section (X Variables)
    st.markdown("---")
    st.markdown("### ⚙️ Enter Equipment Sensor Readings and Operational Data (X Variables)")

    col1, col2, col3 = st.columns(3)

    input_data = {}

    # Categorical Inputs
    with col1:
        st.caption("**Categorical Variables**")
        input_data['Equipment_Type'] = st.selectbox(
            "Equipment Type",
            options=CAT_FEATURES['Equipment_Type'],
            index=1
        )
        input_data['Operator_Shift'] = st.selectbox(
            "Operator Shift",
            options=CAT_FEATURES['Operator_Shift'],
            index=0
        )
        input_data['Record_ID'] = st.number_input("Record ID (Placeholder)", value=1001, step=1)

    # Numerical Inputs
    with col2:
        st.caption("**Numerical Variables (Group 1)**")
        input_data['Runtime_Hours'] = st.number_input("Runtime Hours", value=450.5, format="%.1f")
        input_data['Load_Factor'] = st.slider("Load Factor", min_value=0.0, max_value=1.0, value=0.75, step=0.01)
        input_data['Bearing_Temp_C'] = st.number_input("Bearing Temp (°C)", value=75.2, format="%.1f")
        input_data['Vibration_X_RMS'] = st.number_input("Vibration X RMS", value=1.5, format="%.2f")
        input_data['Energy_Consumption_kwh'] = st.number_input("Energy Consumption (kwh)", value=1500.0, format="%.1f")

    with col3:
        st.caption("**Numerical Variables (Group 2)**")
        input_data['Last_Maintenance_Days'] = st.number_input("Days Since Maint.", value=30, step=1)
        input_data['Oil_Quality_Index'] = st.slider("Oil Quality Index", min_value=0.0, max_value=1.0, value=0.9, step=0.01)
        input_data['Hydraulic_Pressure_psi'] = st.number_input("Hydraulic Pressure (psi)", value=2500.0, format="%.1f")
        input_data['Ambient_Temp_C'] = st.number_input("Ambient Temp (°C)", value=22.0, format="%.1f")
        input_data['Humidity_%'] = st.number_input("Humidity (%)", value=65.0, format="%.1f")

    # --- Prediction ---
    if st.button("Predict Required Spare Part"):

        # 1. Define the complete list of features expected by the model
        all_features = [
            'Record_ID', 'Equipment_Type', 'Runtime_Hours', 'Load_Factor', 'Cycles_Per_Shift',
            'Energy_Consumption_kwh', 'Last_Maintenance_Days', 'Vibration_X_RMS',
            'Vibration_Y_RMS', 'Bearing_Temp_C', 'Hydraulic_Pressure_psi',
            'Motor_Current_Amp', 'Noise_dB', 'Oil_Quality_Index', 'Gearbox_Torque_Nm',
            'Latency_ms', 'Control_Unit_Error_Rate', 'Humidity_%', 'Ambient_Temp_C',
            'Operator_Shift', 'Cargo_Density_Index', 'Required_Spare_Part'
        ]

        # 2. Helper function to get default values for features not collected from UI
        def get_default_value(col):
            if col in NUM_FEATURES:
                return 0.0
            elif col in ['Equipment_Type', 'Operator_Shift']:
                return CAT_FEATURES.get(col, [''])[0]
            elif col == 'Record_ID':
                return 1001
            elif col == 'Required_Spare_Part':
                 return CAT_FEATURES['Required_Spare_Part'][0]
            return ''

        # 3. Create the input dictionary
        full_input_dict = {
            col: [input_data.get(col, get_default_value(col))]
            for col in all_features
        }

        # 4. Create a DataFrame for prediction, ensuring column order matches the model's expectation
        input_df = pd.DataFrame(full_input_dict)[pipeline.feature_names_in_]

        st.markdown("### 💡 Prediction Result")

        # 5. Make Prediction (Y Variable)
        prediction = pipeline.predict(input_df)[0]
        prediction_proba = pipeline.predict_proba(input_df)[0]

        # 6. Display Results
        st.success(f"**Predicted Required Spare Part:** `{prediction}`")

        # Display the probability distribution (confidence)
        proba_df = pd.DataFrame({
            'Spare Part': pipeline.classes_,
            'Probability': prediction_proba
        }).sort_values(by='Probability', ascending=False).reset_index(drop=True)

        st.markdown("**Prediction Confidence (Probability):**")
        st.dataframe(proba_df.style.format({'Probability': "{:.2%}"}), use_container_width=True, hide_index=True)

        st.markdown("---")
        st.info(
            f"""
            This prediction of **{prediction}** informs your inventory.
            By predicting the required part, you can focus on **optimizing inventory
            based on the cost of downtime** associated with this specific component
            vs. its holding cost.
            """
        )

# Run the app
if __name__ == "__main__":
    main()